spring:
  application:
    name: test
  ai:
    dashscope:
      api-key: sk-aab6e95b57ef477a9c830fe5c2db675b
      model: qvq-max
  datasource:
    url: jdbc:mysql://localhost:3306/software_c?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: lysandra061014
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Coze properties
coze:
  api:
    token: sat_5PG6zkvZ0UkGQTKO5DTyxB7TINxIOMBJY0QbXidtWO60jiG5ltkcHKnotqSwkfsJ
    botId-ppt: 7524921627365769256
    botId-video: 7529037562594836499
    baseUrl:  https://api.coze.cn
# 火山引擎
volc:
  api-key: 81dc70b0-c3c6-4387-a225-27b1051b349f
  img-model: doubao-seedream-3-0-t2i-250415
  chat-model: doubao-seed-1-6-250615
  prompt: ",以米字格字帖样式生成"
avatar:
  url: wss://avatar.cn-huadong-1.xf-yun.com/v1/interact
  apiKey: f48991e553870afc6ffb6a8005318586
  apiSecret: MmRhYmIwODlmODJkYjJlMmFlNDE0MTEy
  appId: 19dfb801
  avatarId: 110017006
  vcn: x4_xiaozhong
  sceneId: 215316453426073600
taichuai:
  url: http://10.10.5.59/ds7b/v1/chat/completions
  llm:
    prompt: "请你作为一个精通书法的教学辅助角色为我提供教案"
    model: DeepSeek-R1-Distill-Qwen-7B
    temperature: 0.6
    max_tokens: 1024
server:
  port: 2121
